// Hand-written Custom bodies for the generated bytes domain (namespace idakit_gen). Raw byte reads,
// typed scalar reads (throw when any covered byte is uninitialized), string-literal decode, item
// classification, linear navigation, compiled-pattern search, and byte patching over bytes.hpp. SDK
// symbols that share a generated name are qualified with :: to avoid recursing into this namespace.
// min_ea/max_ea are templated, not here.

#include <pro.h>
#include <ida.hpp>

#include <bytes.hpp> // get_bytes, get_byte/word/dword/qword, is_loaded, is_mapped, get_flags,
                     // get_item_head, get_item_end, next_head, prev_head, get_cmt,
                     // get_strlit_contents, get_max_strlit_length, parse_binpat_str, bin_search,
                     // patch_bytes, compiled_binpat_vec_t, GMB_READALL, ALOPT_IGNHEADS,
                     // STRCONV_REPLCHAR, PBSENC_DEF1BPU, BIN_SEARCH_NOBREAK, BIN_SEARCH_NOSHOW

#include <stdexcept>
#include <string>
#include <vector>

#include "gen_bytes.h"
// The generated bridge header defines the shared structs (BinpatStats needs its full definition to
// construct below); gen_bytes.h only forward-declares them.
#include "gen_bridge.h"

namespace idakit_gen {

namespace {
// A typed read must fail cleanly on a partly-mapped range, so gate on every covered byte.
bool range_loaded(ea_t ea, size_t n) {
  for (size_t i = 0; i < n; i++)
    if (!is_loaded(ea + i))
      return false;
  return true;
}
} // namespace

rust::Vec<uint8_t> get_bytes(uint64_t ea, size_t size) {
  std::vector<uint8_t> buf(size);
  int64_t r = (int64_t)::get_bytes(buf.data(), (ssize_t)size, (ea_t)ea, GMB_READALL);
  if (r < 0)
    throw std::runtime_error("get_bytes failed: unmapped range");
  return to_rust_bytes(buf.data(), size);
}

uint8_t get_u8(uint64_t ea) {
  if (!range_loaded((ea_t)ea, 1))
    throw std::runtime_error("get_u8: byte uninitialized");
  return (uint8_t)get_byte((ea_t)ea);
}

uint16_t get_u16(uint64_t ea) {
  if (!range_loaded((ea_t)ea, 2))
    throw std::runtime_error("get_u16: covered byte uninitialized");
  return (uint16_t)get_word((ea_t)ea);
}

uint32_t get_u32(uint64_t ea) {
  if (!range_loaded((ea_t)ea, 4))
    throw std::runtime_error("get_u32: covered byte uninitialized");
  return (uint32_t)get_dword((ea_t)ea);
}

uint64_t get_u64(uint64_t ea) {
  if (!range_loaded((ea_t)ea, 8))
    throw std::runtime_error("get_u64: covered byte uninitialized");
  return (uint64_t)get_qword((ea_t)ea);
}

rust::String get_strlit(uint64_t ea, int32_t strtype) {
  size_t len = get_max_strlit_length((ea_t)ea, strtype, ALOPT_IGNHEADS);
  if (len == 0)
    throw std::runtime_error("no string literal at address");
  qstring out;
  ssize_t r = get_strlit_contents(&out, (ea_t)ea, len, strtype, nullptr, STRCONV_REPLCHAR);
  if (r < 0)
    throw std::runtime_error("undecodable string literal");
  return to_rust_string(out);
}

uint64_t get_flags(uint64_t ea) { return (uint64_t)::get_flags((ea_t)ea); }

uint64_t get_item_head(uint64_t ea) { return (uint64_t)::get_item_head((ea_t)ea); }

uint64_t get_item_end(uint64_t ea) { return (uint64_t)::get_item_end((ea_t)ea); }

uint64_t get_next_head(uint64_t ea, uint64_t maxea) {
  return (uint64_t)next_head((ea_t)ea, (ea_t)maxea);
}

uint64_t get_prev_head(uint64_t ea, uint64_t minea) {
  return (uint64_t)prev_head((ea_t)ea, (ea_t)minea);
}

rust::String get_cmt(uint64_t ea, bool rptble) {
  qstring out;
  if (::get_cmt(&out, (ea_t)ea, rptble) < 0)
    throw std::runtime_error("no comment at address");
  return to_rust_string(out);
}

std::unique_ptr<::compiled_binpat_vec_t> binpat_compile(uint64_t ea, rust::Str pattern,
                                                        int32_t radix) {
  auto out = std::make_unique<compiled_binpat_vec_t>();
  std::string pat(pattern.data(), pattern.size());
  qstring err;
  if (!parse_binpat_str(out.get(), (ea_t)ea, pat.c_str(), radix, PBSENC_DEF1BPU, &err))
    throw std::runtime_error(err.empty() ? "unparseable pattern" : err.c_str());
  return out;
}

std::unique_ptr<::compiled_binpat_vec_t> binpat_from_bytes(rust::Slice<const uint8_t> bytes,
                                                           rust::Slice<const uint8_t> mask) {
  auto out = std::make_unique<compiled_binpat_vec_t>();
  compiled_binpat_t &b = out->push_back();
  b.bytes.append(bytes.data(), bytes.size());
  if (!mask.empty())
    b.mask.append(mask.data(), mask.size());
  return out;
}

BinpatStats binpat_stats(const ::compiled_binpat_vec_t &pat) {
  BinpatStats out{};
  if (!pat.empty()) {
    const compiled_binpat_t &b = pat.front();
    out.total = b.bytes.size();
    if (b.mask.empty()) {
      out.anchors = out.total;
    } else {
      for (size_t i = 0; i < b.mask.size(); i++)
        if (b.mask[i] != 0)
          out.anchors++;
    }
  }
  return out;
}

uint64_t bin_search(uint64_t start, uint64_t end, const ::compiled_binpat_vec_t &pat,
                    int32_t flags) {
  // NOBREAK/NOSHOW are mandatory headless: no Ctrl-Break polling, no UI progress.
  ea_t hit =
      ::bin_search((ea_t)start, (ea_t)end, pat, flags | BIN_SEARCH_NOBREAK | BIN_SEARCH_NOSHOW);
  return (uint64_t)hit;
}

bool patch_bytes(uint64_t ea, rust::Slice<const uint8_t> bytes) {
  if (bytes.empty())
    return true;
  // Reject a write whose last byte wraps past 2^64: unsigned `ea + i` would otherwise fold to a low
  // address and silently patch the wrong region.
  if (ea + (bytes.size() - 1) < ea)
    return false;
  // Reject the whole write if any target byte is outside the address space, so a bad address fails
  // cleanly instead of silently patching a truncated prefix.
  for (size_t i = 0; i < bytes.size(); i++)
    if (!is_mapped((ea_t)ea + i))
      return false;
  ::patch_bytes((ea_t)ea, bytes.data(), bytes.size());
  return true;
}

} // namespace idakit_gen
