// idakit facade: the zero-copy byte read into a caller buffer. The owning twin (get_bytes -> Vec),
// pattern search, and patching are cxx bridges in the generated bytes domain
// (facade/bytes_custom.cc).

#include <pro.h>

#include <ida.hpp>

#include <bytes.hpp>

#include "idakit_facade.h"

extern "C" int64_t idakit_get_bytes(idakit_ea_t ea, void *buf, size_t size) {
  return (int64_t)get_bytes(buf, (ssize_t)size, (ea_t)ea, GMB_READALL);
}
