/* idakit facade: a clean C ABI over the C++ IDA SDK surface.
 * Opaque handles + free functions; strings copied out into caller buffers.
 * This header is what idakit-sys binds (hand-extern for now, bindgen later). */
#ifndef IDAKIT_FACADE_H
#define IDAKIT_FACADE_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef uint64_t idakit_ea_t; /* ea_t under __EA64__ */

/* Force headless (TVHEADLESS) then init_library; returns its rc (0 = ok). Wrapping keeps
 * the setenv ordered before init and the side effect on the C++ side. */
int idakit_init_library(void);

/* Set IDA's `batch` global: nonzero suppresses dialogs and auto-answers prompts (headless
 * default), zero restores interactive behavior (e.g. a GUI-plugin host). */
void idakit_set_batch(int on);

/* Fatal-exit trap. idakit_guarded_open returns this sentinel (instead of an
 * open_database rc) when the kernel tried to terminate the process mid-call; the
 * intercepted exit code is then available from idakit_last_exit_code(). */
#define IDAKIT_EXIT_TRAPPED (-0x7FFFFFFF)
int idakit_guarded_open(const char *file_path, int run_auto);
int idakit_guarded_auto_wait(void); /* 1 ok / 0 fail / IDAKIT_EXIT_TRAPPED */
int idakit_guarded_close(int save); /* 0 ok / IDAKIT_EXIT_TRAPPED */
int idakit_last_exit_code(void);
int idakit_was_trapped(void); /* 1 if the last guarded call trapped a fatal exit */
size_t idakit_last_output(char *buf, size_t cap); /* captured stdout+stderr; len, snprintf-style */

int idakit_reg_read_int(const char *name, int defval); /* read an int/bool registry value */
int idakit_accept_eula(void); /* record EULA acceptance; returns its value */

/* Fault-injection hooks for the trap and cxx tests. Inert in normal use: idakit_test_fatal arms
 * its own guarded<> so it always traps and returns rather than terminating, and
 * idakit_trigger_fatal fires a fatal only when invoked with no guard on the stack. The Rust
 * bindings are #[doc(hidden)], keeping them off the published API. */
#define IDAKIT_FATAL_EXIT 0
#define IDAKIT_FATAL_ABORT 1
#define IDAKIT_FATAL_INTERR 2
int idakit_test_fatal(int kind);
int idakit_get_batch(void); /* read back the `batch` global, to prove bring-up wired it */
/* Fire a fatal (IDAKIT_FATAL_*) from any TU; the exit/abort stand-ins are file-local to
 * runtime.cpp, so the cxx probe body calls this to reach them. */
void idakit_trigger_fatal(int kind);
/* Arm guarded<>, then call the cxx-generated shim for probe_fatal_through_cxx from inside it, so
 * the fatal's longjmp must cross the shim's try/catch frame. Returns IDAKIT_EXIT_TRAPPED when the
 * longjmp fired (exit/abort), or 1 when cxx caught the throw first (interr) and reported an Err. */
int idakit_test_fatal_through_cxx(int kind);

/* The zero-copy read into a caller buffer, <0 on fail. The owning twin (Vec), pattern search,
 * and patching are cxx bridges in the generated bytes domain. */
int64_t idakit_get_bytes(idakit_ea_t ea, void *buf, size_t size);

int idakit_hexrays_init(void); /* 1 = decompiler ready, 0 = unavailable */

/* Hex-Rays cfunc cache (hexrays.hpp). Each guards on a null HEXDSP (decompiler not yet
   initialized, so nothing is cached) and returns the empty answer. */
int idakit_mark_cfunc_dirty(idakit_ea_t ea, int close_views); /* 1 if an entry existed */
void idakit_clear_cached_cfuncs(void);
int idakit_has_cached_cfunc(idakit_ea_t ea); /* 1 if cached */

/* Streaming ctree extraction. The facade is a pure SDK walker: it reads a decompiled
 * function's ctree depth-first and, per node, calls one Rust callback in `vtbl` to mint
 * the corresponding owned node. Children are emitted before their parent (post-order),
 * so each callback receives its children as the `uint32_t` handles their own callbacks
 * returned; the facade just threads them through the recursion. The facade owns no node
 * storage and does no interning; all identity, dedup, and meaning live on the Rust side.
 *
 * Handles are opaque to the facade. `0xFFFFFFFF` (IDAKIT_NONE) marks an absent optional
 * child. `ctx` is passed back to every callback untouched. */
#define IDAKIT_NONE 0xFFFFFFFFu

/* One switch case: its `values` (empty = default) and `body` statement handle. */
typedef struct {
  const uint64_t *values;
  size_t nvalues;
  uint32_t body;
} idakit_case_t;

/* Type-apply result codes (shared with the generated type-build bridge; decoded by idakit against
 * TypeWriteResult.code):
 *   OK        parsed/resolved and applied
 *   ERR_INPUT parse failed, or no such named type
 *   ERR_APPLY apply_tinfo rejected the type at ea */
#define IDAKIT_TYPE_OK 0
#define IDAKIT_TYPE_ERR_INPUT 1
#define IDAKIT_TYPE_ERR_APPLY 2

/* Type-recipe opcodes: a postfix (RPN) bytecode idakit serializes a type builder into, walked by
 * the generated bridge's recipe apply path over a tinfo_t stack. A leaf op pushes a type; a
 * transform op pops one and pushes the wrapped result; a well-formed recipe leaves exactly one
 * type. Multi-byte operands are little-endian. Kept in lockstep with ty_build.rs by hand (no shared
 * codegen). */
#define IDAKIT_RECIPE_VOID 0
#define IDAKIT_RECIPE_BOOL 1
#define IDAKIT_RECIPE_INT 2      /* + u8 bytes, u8 signed */
#define IDAKIT_RECIPE_FLOAT 3    /* + u8 bytes */
#define IDAKIT_RECIPE_NAMED 4    /* + u32 len, then len name bytes */
#define IDAKIT_RECIPE_DECL 5     /* + u32 len, then len decl bytes */
#define IDAKIT_RECIPE_PTR 6      /* pop 1, push pointer-to */
#define IDAKIT_RECIPE_ARRAY 7    /* + u64 nelems; pop 1, push array-of */
#define IDAKIT_RECIPE_CONST 8    /* pop 1, push const-qualified */
#define IDAKIT_RECIPE_VOLATILE 9 /* pop 1, push volatile-qualified */
#define IDAKIT_RECIPE_FUNCTION                                                                     \
  10 /* + u32 nparams, u8 varargs, u16 cc, then nparams u32-len-prefixed names; pops nparams param \
        types then the return type (return pushed first, params in order), push the function type. \
      */

/* Prototype-surgery result codes (IDAKIT_SIG_*), shared with the generated type-build bridge and
 * decoded by idakit against TypeWriteResult.code. */
#define IDAKIT_SIG_OK 0
#define IDAKIT_SIG_NO_PROTOTYPE 1 /* ea has no function type to edit */
#define IDAKIT_SIG_ARG_RANGE 2    /* arg index >= parameter count */
#define IDAKIT_SIG_BUILD 3        /* a replacement-type recipe did not build */
#define IDAKIT_SIG_APPLY 4        /* create_func or apply_tinfo rejected the rebuilt signature */

/* Member-edit result codes (IDAKIT_TEDIT_* and IDAKIT_MEMBER_APPEND), shared with the generated
 * type-build bridge. The edit returns 0 on success, a positive IDAKIT_TEDIT_* sentinel for an
 * idakit-side pre-failure, or the negative raw tinfo_code_t the kernel returned (mirrored by the
 * TypeEditCode enum). */
#define IDAKIT_TEDIT_NO_TYPE 1              /* no such named type in the local til */
#define IDAKIT_TEDIT_NO_MEMBER 2            /* the member (name/offset) did not resolve */
#define IDAKIT_TEDIT_BUILD 3                /* a member-type recipe did not build */
#define IDAKIT_MEMBER_APPEND ((uint64_t)-1) /* add at the end rather than a fixed offset */

/* One fragment of a scattered (ALOC_DIST) local's location. `atype` is the fragment's own
 * ALOC_* (register or stack); `reg`/`sval` hold its register or stack offset; off/size give the
 * byte range of the whole value this fragment covers. */
typedef struct idakit_loc_piece_t {
  uint32_t atype;
  uint32_t reg;
  int64_t sval;
  uint32_t off;
  uint32_t size;
} idakit_loc_piece_t;

/* A local variable's location, decoded from IDA's argloc_t. `atype` is the ALOC_* discriminant;
 * only the fields it selects are meaningful: reg1 (REG1/REG2 low/RREL reg), reg2 (REG2 high),
 * sval (STACK offset / STATIC ea / RREL displacement). pieces/npieces describe a scattered
 * location and are null/0 otherwise. The pieces array is a walk-owned temporary, valid only for
 * the l_lvar call it is passed to. */
typedef struct idakit_lvar_loc_t {
  uint32_t atype;
  uint32_t reg1;
  uint32_t reg2;
  int64_t sval;
  const idakit_loc_piece_t *pieces;
  uint32_t npieces;
} idakit_lvar_loc_t;

/* The callbacks the facade invokes while walking. Every function returns the handle of
 * the node/type it minted (except the void ones). Scalar `kind` codes and `ctype` values
 * are interpreted on the Rust side. `ty` is the node's resolved type handle.
 *
 * Pointer lifetime: every `const char*`/byte span passed to a callback (names, string
 * literals, member/enum-constant names, comments, value arrays) points into a C++ stack
 * temporary owned by the walk, a local `qstring`, `udt_type_data_t`, `enum_type_data_t`,
 * or `std::vector`. It is borrowed for that single callback invocation only and is
 * invalidated as soon as the callback returns; a callback that needs it longer must copy
 * it before returning. */
typedef struct idakit_emit_vtbl_t {
  /* expressions */
  uint32_t (*e_num)(void *ctx, idakit_ea_t ea, uint64_t value, uint32_t ty);
  uint32_t (*e_fnum)(void *ctx, idakit_ea_t ea, double value, uint32_t ty);
  uint32_t (*e_obj)(void *ctx, idakit_ea_t ea, idakit_ea_t target, const char *name,
                    size_t name_len, uint32_t ty);
  uint32_t (*e_var)(void *ctx, idakit_ea_t ea, uint32_t idx, uint32_t ty);
  uint32_t (*e_str)(void *ctx, idakit_ea_t ea, const char *s, size_t len, uint32_t ty);
  uint32_t (*e_helper)(void *ctx, idakit_ea_t ea, const char *s, size_t len, uint32_t ty);
  uint32_t (*e_call)(void *ctx, idakit_ea_t ea, uint32_t callee, const uint32_t *args, size_t nargs,
                     uint32_t ty);
  uint32_t (*e_memref)(void *ctx, idakit_ea_t ea, uint32_t obj, uint32_t offset, uint32_t ty);
  uint32_t (*e_memptr)(void *ctx, idakit_ea_t ea, uint32_t obj, uint32_t offset, uint32_t ty);
  uint32_t (*e_deref)(void *ctx, idakit_ea_t ea, uint32_t x, uint32_t size, uint32_t ty);
  /* generic operator node: binary/assign/unary/ternary/cast/index/sizeof/empty/type/insn.
   * `ctype` is the raw ctype_t; absent operands are IDAKIT_NONE. */
  uint32_t (*e_op)(void *ctx, idakit_ea_t ea, uint32_t ctype, uint32_t x, uint32_t y, uint32_t z,
                   uint32_t ty);

  /* statements */
  uint32_t (*s_block)(void *ctx, idakit_ea_t ea, const uint32_t *kids, size_t nkids);
  uint32_t (*s_expr)(void *ctx, idakit_ea_t ea, uint32_t expr);
  uint32_t (*s_if)(void *ctx, idakit_ea_t ea, uint32_t cond, uint32_t then_s, uint32_t else_s);
  uint32_t (*s_for)(void *ctx, idakit_ea_t ea, uint32_t init, uint32_t cond, uint32_t step,
                    uint32_t body);
  uint32_t (*s_while)(void *ctx, idakit_ea_t ea, uint32_t cond, uint32_t body);
  uint32_t (*s_do)(void *ctx, idakit_ea_t ea, uint32_t body, uint32_t cond);
  uint32_t (*s_switch)(void *ctx, idakit_ea_t ea, uint32_t expr, const idakit_case_t *cases,
                       size_t ncases);
  uint32_t (*s_break)(void *ctx, idakit_ea_t ea);
  uint32_t (*s_continue)(void *ctx, idakit_ea_t ea);
  uint32_t (*s_return)(void *ctx, idakit_ea_t ea, uint32_t expr /* or IDAKIT_NONE */);
  uint32_t (*s_goto)(void *ctx, idakit_ea_t ea, int32_t label);
  uint32_t (*s_asm)(void *ctx, idakit_ea_t ea, const uint64_t *addrs, size_t n);
  uint32_t (*s_try)(void *ctx, idakit_ea_t ea, uint32_t body, const uint32_t *catches, size_t n);
  uint32_t (*s_throw)(void *ctx, idakit_ea_t ea, uint32_t expr /* or IDAKIT_NONE */);
  uint32_t (*s_empty)(void *ctx, idakit_ea_t ea);

  /* locals. Append one lvar; the call order is the lvar index that `e_var.idx` refers to. flags:
   * bit0 is_arg, bit1 is_result, bit2 is_byref. `loc` carries the decoded argloc_t. */
  void (*l_lvar)(void *ctx, const char *name, size_t name_len, uint32_t ty, uint32_t flags,
                 uint32_t width, const char *comment, size_t comment_len,
                 const idakit_lvar_loc_t *loc);
} idakit_emit_vtbl_t;

/* Walk `cfunc`'s ctree, driving `vtbl` (with `ctx`) for nodes and `visitor` (an opaque
 * idakit_cxx::TypeWalkVisitor*) for each node's type, writing the root statement handle to `*root`.
 * Returns 0 on success, non-zero if any of `cfunc`/`vtbl`/`visitor`/`root` is NULL. */
int idakit_cfunc_walk_ctree(void *cfunc, const idakit_emit_vtbl_t *vtbl, void *ctx, void *visitor,
                            uint32_t *root);

/* Instruction-decode sentinels shared with the generated decode bridge and the Rust
 * idakit_sys::IDAKIT_* consts; the bridge caps populated operands at IDAKIT_MAX_OPS. */
#define IDAKIT_MAX_OPS 8

/* Semantic operand kind codes (raw optype folded away). */
#define IDAKIT_OP_REG 0
#define IDAKIT_OP_MEM 1
#define IDAKIT_OP_IMM 2
#define IDAKIT_OP_NEAR 3
#define IDAKIT_OP_FAR 4

/* Sentinel for an absent base/index register. */
#define IDAKIT_REG_NONE 0xFFFF

/* Instruction control-flow bit flags. */
#define IDAKIT_FLOW_CALL 0x01
#define IDAKIT_FLOW_RET 0x02
#define IDAKIT_FLOW_JUMP 0x04
#define IDAKIT_FLOW_INDIRECT 0x08
#define IDAKIT_FLOW_STOPS 0x10

#ifdef __cplusplus
}
#endif

#endif /* IDAKIT_FACADE_H */
