/* idakit facade: a clean C ABI over the C++ IDA SDK surface.
 * Opaque handles + free functions; strings copied out into caller buffers.
 * This header is what idakit-sys binds (hand-extern for now, bindgen later). */
#ifndef IDAKIT_FACADE_H
#define IDAKIT_FACADE_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef uint64_t idakit_ea_t; /* ea_t under __EA64__ */

/* Force headless (TVHEADLESS) then init_library; returns its rc (0 = ok). Wrapping keeps
 * the setenv ordered before init and the side effect on the C++ side. */
int idakit_init_library(void);

/* Set IDA's `batch` global: nonzero suppresses dialogs and auto-answers prompts (headless
 * default), zero restores interactive behavior (e.g. a GUI-plugin host). */
void idakit_set_batch(int on);

/* Fatal-exit trap. idakit_guarded_open returns this sentinel (instead of an
 * open_database rc) when the kernel tried to terminate the process mid-call; the
 * intercepted exit code is then available from idakit_last_exit_code(). */
#define IDAKIT_EXIT_TRAPPED (-0x7FFFFFFF)
int idakit_guarded_open(const char *file_path, int run_auto);
int idakit_guarded_auto_wait(void); /* 1 ok / 0 fail / IDAKIT_EXIT_TRAPPED */
int idakit_guarded_close(int save); /* 0 ok / IDAKIT_EXIT_TRAPPED */
int idakit_last_exit_code(void);
int idakit_was_trapped(void); /* 1 if the last guarded call trapped a fatal exit */
size_t idakit_last_output(char *buf, size_t cap); /* captured stdout+stderr; len, snprintf-style */

int idakit_reg_read_int(const char *name, int defval); /* read an int/bool registry value */
int idakit_accept_eula(void); /* record EULA acceptance; returns its value */

/* Fault-injection hooks for the trap and cxx tests. Inert in normal use: idakit_test_fatal arms
 * its own guarded<> so it always traps and returns rather than terminating, and
 * idakit_trigger_fatal fires a fatal only when invoked with no guard on the stack. The Rust
 * bindings are #[doc(hidden)], keeping them off the published API. */
#define IDAKIT_FATAL_EXIT 0
#define IDAKIT_FATAL_ABORT 1
#define IDAKIT_FATAL_INTERR 2
int idakit_test_fatal(int kind);
int idakit_get_batch(void); /* read back the `batch` global, to prove bring-up wired it */
/* Fire a fatal (IDAKIT_FATAL_*) from any TU; the exit/abort stand-ins are file-local to
 * runtime.cpp, so the cxx probe body calls this to reach them. */
void idakit_trigger_fatal(int kind);
/* Arm guarded<>, then call the cxx-generated shim for probe_fatal_through_cxx from inside it, so
 * the fatal's longjmp must cross the shim's try/catch frame. Returns IDAKIT_EXIT_TRAPPED when the
 * longjmp fired (exit/abort), or 1 when cxx caught the throw first (interr) and reported an Err. */
int idakit_test_fatal_through_cxx(int kind);

/* The zero-copy read into a caller buffer, <0 on fail. The owning twin (Vec), pattern search,
 * and patching are cxx bridges in the generated bytes domain. */
int64_t idakit_get_bytes(idakit_ea_t ea, void *buf, size_t size);

/* Type-apply result codes (shared with the generated type-build bridge; decoded by idakit against
 * TypeWriteResult.code):
 *   OK        parsed/resolved and applied
 *   ERR_INPUT parse failed, or no such named type
 *   ERR_APPLY apply_tinfo rejected the type at ea */
#define IDAKIT_TYPE_OK 0
#define IDAKIT_TYPE_ERR_INPUT 1
#define IDAKIT_TYPE_ERR_APPLY 2

/* Type-recipe opcodes: a postfix (RPN) bytecode idakit serializes a type builder into, walked by
 * the generated bridge's recipe apply path over a tinfo_t stack. A leaf op pushes a type; a
 * transform op pops one and pushes the wrapped result; a well-formed recipe leaves exactly one
 * type. Multi-byte operands are little-endian. Kept in lockstep with ty_build.rs by hand (no shared
 * codegen). */
#define IDAKIT_RECIPE_VOID 0
#define IDAKIT_RECIPE_BOOL 1
#define IDAKIT_RECIPE_INT 2      /* + u8 bytes, u8 signed */
#define IDAKIT_RECIPE_FLOAT 3    /* + u8 bytes */
#define IDAKIT_RECIPE_NAMED 4    /* + u32 len, then len name bytes */
#define IDAKIT_RECIPE_DECL 5     /* + u32 len, then len decl bytes */
#define IDAKIT_RECIPE_PTR 6      /* pop 1, push pointer-to */
#define IDAKIT_RECIPE_ARRAY 7    /* + u64 nelems; pop 1, push array-of */
#define IDAKIT_RECIPE_CONST 8    /* pop 1, push const-qualified */
#define IDAKIT_RECIPE_VOLATILE 9 /* pop 1, push volatile-qualified */
#define IDAKIT_RECIPE_FUNCTION                                                                     \
  10 /* + u32 nparams, u8 varargs, u16 cc, then nparams u32-len-prefixed names; pops nparams param \
        types then the return type (return pushed first, params in order), push the function type. \
      */

/* Prototype-surgery result codes (IDAKIT_SIG_*), shared with the generated type-build bridge and
 * decoded by idakit against TypeWriteResult.code. */
#define IDAKIT_SIG_OK 0
#define IDAKIT_SIG_NO_PROTOTYPE 1 /* ea has no function type to edit */
#define IDAKIT_SIG_ARG_RANGE 2    /* arg index >= parameter count */
#define IDAKIT_SIG_BUILD 3        /* a replacement-type recipe did not build */
#define IDAKIT_SIG_APPLY 4        /* create_func or apply_tinfo rejected the rebuilt signature */

/* Member-edit result codes (IDAKIT_TEDIT_* and IDAKIT_MEMBER_APPEND), shared with the generated
 * type-build bridge. The edit returns 0 on success, a positive IDAKIT_TEDIT_* sentinel for an
 * idakit-side pre-failure, or the negative raw tinfo_code_t the kernel returned (mirrored by the
 * TypeEditCode enum). */
#define IDAKIT_TEDIT_NO_TYPE 1              /* no such named type in the local til */
#define IDAKIT_TEDIT_NO_MEMBER 2            /* the member (name/offset) did not resolve */
#define IDAKIT_TEDIT_BUILD 3                /* a member-type recipe did not build */
#define IDAKIT_MEMBER_APPEND ((uint64_t)-1) /* add at the end rather than a fixed offset */

/* Instruction-decode sentinels shared with the generated decode bridge and the Rust
 * idakit_sys::IDAKIT_* consts; the bridge caps populated operands at IDAKIT_MAX_OPS. */
#define IDAKIT_MAX_OPS 8

/* Semantic operand kind codes (raw optype folded away). */
#define IDAKIT_OP_REG 0
#define IDAKIT_OP_MEM 1
#define IDAKIT_OP_IMM 2
#define IDAKIT_OP_NEAR 3
#define IDAKIT_OP_FAR 4

/* Sentinel for an absent base/index register. */
#define IDAKIT_REG_NONE 0xFFFF

/* Instruction control-flow bit flags. */
#define IDAKIT_FLOW_CALL 0x01
#define IDAKIT_FLOW_RET 0x02
#define IDAKIT_FLOW_JUMP 0x04
#define IDAKIT_FLOW_INDIRECT 0x08
#define IDAKIT_FLOW_STOPS 0x10

#ifdef __cplusplus
}
#endif

#endif /* IDAKIT_FACADE_H */
