//! Instruction-decode sentinels shared with the generated decode bridge: control-flow flags and
//! operand access bits. The scalar sentinels (`MAX_OPS`, `OP_*`, `REG_NONE`, `FLOW_*`) are
//! generated by `idakit-sys-codegen`'s `instruction` domain spec.

use bitflags::bitflags;

bitflags! {
    /// `InstructionData::flow` control-flow bits for a decoded instruction: [`crate::FLOW_CALL`]/
    /// [`crate::FLOW_RET`]/[`crate::FLOW_JUMP`]/[`crate::FLOW_INDIRECT`]/[`crate::FLOW_STOPS`].
    ///
    /// `FLOW_*` is idakit's own facade sentinel, not a raw SDK value; accepts any bit pattern
    /// (`from_bits_retain`), since `InstructionData::flow` is a raw `u8` field the C++ decoder
    /// writes.
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Default)]
    pub struct FlowFlags: u8 {
        /// The instruction is a call.
        const CALL = crate::FLOW_CALL;
        /// The instruction returns.
        const RET = crate::FLOW_RET;
        /// The instruction jumps.
        const JUMP = crate::FLOW_JUMP;
        /// The transfer target is indirect, not statically known.
        const INDIRECT = crate::FLOW_INDIRECT;
        /// Sequential flow stops after this instruction.
        const STOPS = crate::FLOW_STOPS;
    }
}

bitflags! {
    /// `OperandData::access` bits for a decoded operand: `bit0` read, `bit1` written.
    ///
    /// Accepts any bit pattern (`from_bits_retain`), since `OperandData::access` is a raw `u8`
    /// field the C++ decoder writes.
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Default)]
    pub struct OperandAccess: u8 {
        /// The operand is read.
        const READ = 1;
        /// The operand is written.
        const WRITTEN = 2;
    }
}

#[cfg(test)]
mod tests {
    use assert2::assert;

    use super::*;

    #[test]
    fn flags_pin_the_generated_facade_values() {
        assert!(FlowFlags::CALL.bits() == crate::FLOW_CALL);
        assert!(FlowFlags::RET.bits() == crate::FLOW_RET);
        assert!(FlowFlags::JUMP.bits() == crate::FLOW_JUMP);
        assert!(FlowFlags::INDIRECT.bits() == crate::FLOW_INDIRECT);
        assert!(FlowFlags::STOPS.bits() == crate::FLOW_STOPS);
    }

    #[test]
    fn from_bits_retain_preserves_unknown_bits() {
        let raw = (FlowFlags::CALL | FlowFlags::STOPS).bits() | 0x40;
        let flow = FlowFlags::from_bits_retain(raw);
        assert!(flow.contains(FlowFlags::CALL | FlowFlags::STOPS));
        assert!(flow.bits() == raw);
    }

    #[test]
    fn operand_access_flags_pin_the_raw_values() {
        assert!(OperandAccess::READ.bits() == 1);
        assert!(OperandAccess::WRITTEN.bits() == 2);
    }

    #[test]
    fn operand_access_from_bits_retain_preserves_unknown_bits() {
        let raw = OperandAccess::READ.bits() | 0x04;
        let access = OperandAccess::from_bits_retain(raw);
        assert!(access.contains(OperandAccess::READ));
        assert!(access.bits() == raw);
    }
}
