//! Cross-references: [`Xref`] and its [`XrefKind`] classification. The IDA
//! reference-type byte is in two overlapping spaces (code/data) split here into
//! [`CodeXref`]/[`DataXref`], each a closed mirror of `cref_t`/`dref_t` that
//! rejects a byte outside the set rather than folding it into a catch-all.

use std::ffi::c_void;
use std::marker::PhantomData;

use idakit_sys as sys;
use num_enum::{IntoPrimitive, TryFromPrimitive};
use strum::VariantArray;

use crate::Database;
use crate::address::Address;

impl Database {
    /// Lazily iterate every cross-reference targeting `address` -- its callers and the data
    /// that points at it (ordinary sequential flow excluded).
    #[inline]
    #[must_use]
    pub fn xrefs_to(&self, address: Address) -> Xrefs<'_> {
        Xrefs::new(self.xref_open(address, true))
    }

    /// Lazily iterate every cross-reference originating at `address` -- what the code there
    /// calls, jumps to, or reads (ordinary sequential flow excluded).
    #[inline]
    #[must_use]
    pub fn xrefs_from(&self, address: Address) -> Xrefs<'_> {
        Xrefs::new(self.xref_open(address, false))
    }
}

/// A cross-reference edge, carrying both endpoints. For [`xrefs_to`](Database::xrefs_to) the
/// `to` end is the queried address; for [`xrefs_from`](Database::xrefs_from) the `from` end is.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Xref {
    /// The referencing (source) address.
    pub from: Address,
    /// The referenced (target) address.
    pub to: Address,
    /// How the reference is classified -- code vs data, and its specific type.
    pub kind: XrefKind,
    /// Who created the reference -- IDA's analysis or the user.
    pub origin: XrefOrigin,
}

impl Xref {
    /// Build from the facade's `(from, to, type, iscode, user)` tuple. `None` -- and so skipped by
    /// the iterator -- if either endpoint is `BADADDR`, or if `ty` is outside the modelled
    /// `cref_t`/`dref_t` set (version drift: the set is complete for 9.3, so this does not occur
    /// on real data). `ty` is IDA's already-masked base type; `user` is `xrefblk_t::user`.
    #[inline]
    #[must_use]
    pub(crate) fn from_raw(from: u64, to: u64, ty: u8, iscode: u8, user: u8) -> Option<Self> {
        let from = Address::try_new(from)?;
        let to = Address::try_new(to)?;
        let kind = if iscode != 0 {
            XrefKind::Code(CodeXref::try_from(ty).ok()?)
        } else {
            XrefKind::Data(DataXref::try_from(ty).ok()?)
        };
        let origin = if user != 0 {
            XrefOrigin::User
        } else {
            XrefOrigin::Analysis
        };
        Some(Self {
            from,
            to,
            kind,
            origin,
        })
    }

    /// Whether this is a code reference rather than a data one.
    #[inline]
    #[must_use]
    pub const fn is_code(&self) -> bool {
        matches!(self.kind, XrefKind::Code(_))
    }

    /// Whether the user defined this reference (rather than IDA's analysis).
    #[inline]
    #[must_use]
    pub const fn is_user(&self) -> bool {
        matches!(self.origin, XrefOrigin::User)
    }
}

/// Who created a cross-reference. Mirrors `xrefblk_t::user` (xref.hpp, IDA 9.3).
///
/// IDA regenerates a function's xrefs on every reanalysis, deleting the ones it made and
/// recreating them from the code -- except those a user marked, which carry the `XREF_USER`
/// bit and are preserved. So the distinction is also one of durability: a
/// [`User`](XrefOrigin::User) edge is an explicit annotation, an [`Analysis`](XrefOrigin::Analysis) edge
/// is a derived fact that moves with the code.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum XrefOrigin {
    /// Generated by IDA's auto-analysis (the processor module); recreated on reanalysis.
    Analysis,
    /// Defined by the user; marked `XREF_USER`, so IDA preserves it across reanalysis.
    User,
}

/// Lazy iterator over cross-references; closes the cursor on drop. Borrows `&Database`, so it
/// can't outlive the database or coexist with a write.
pub struct Xrefs<'db> {
    cursor: *mut c_void,
    _db: PhantomData<&'db Database>,
}

impl Xrefs<'_> {
    #[inline]
    pub(crate) fn new(cursor: *mut c_void) -> Self {
        Self {
            cursor,
            _db: PhantomData,
        }
    }
}

impl Iterator for Xrefs<'_> {
    type Item = Xref;

    fn next(&mut self) -> Option<Xref> {
        loop {
            let (mut from, mut to, mut ty, mut iscode, mut user) = (0u64, 0u64, 0u8, 0u8, 0u8);
            // SAFETY: `cursor` came from `idakit_xref_open` and is live until our `Drop`;
            // the out-pointers are valid for this call.
            let ok = unsafe {
                sys::idakit_xref_next(
                    self.cursor,
                    &mut from,
                    &mut to,
                    &mut ty,
                    &mut iscode,
                    &mut user,
                )
            };
            if ok == 0 {
                return None;
            }
            // A `BADADDR` endpoint is not a usable edge; skip it and keep stepping.
            if let Some(reference) = Xref::from_raw(from, to, ty, iscode, user) {
                return Some(reference);
            }
        }
    }
}

impl Drop for Xrefs<'_> {
    fn drop(&mut self) {
        // SAFETY: `cursor` came from `idakit_xref_open` and is closed exactly once here.
        unsafe { sys::idakit_xref_close(self.cursor) };
    }
}

/// A reference classified into the code or data type space.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum XrefKind {
    /// A code reference (call, jump, or ordinary flow).
    Code(CodeXref),
    /// A data reference (read, write, offset, ...).
    Data(DataXref),
}

/// Code cross-reference type -- a closed mirror of IDA's `cref_t` (xref.hpp, IDA 9.3). A byte
/// outside this set does not decode -- its `TryFrom<u8>` conversion fails.
#[derive(
    Clone, Copy, Debug, PartialEq, Eq, Hash, TryFromPrimitive, IntoPrimitive, VariantArray,
)]
#[repr(u8)]
pub enum CodeXref {
    /// `fl_U`: IDA's own "unknown" flow type, kept for compatibility with old databases -- a
    /// real `cref_t` value, not a catch-all for unrecognized bytes.
    Unknown = 0,
    /// A far call.
    CallFar = 16,
    /// A near call.
    CallNear = 17,
    /// A far jump.
    JumpFar = 18,
    /// A near jump.
    JumpNear = 19,
    /// `fl_USobsolete`: an obsolete user-specified code xref; modern IDA does not emit it, kept
    /// for a complete mirror of the SDK set.
    UserObsolete = 20,
    /// Ordinary sequential flow into the next instruction.
    Flow = 21,
}

/// Data cross-reference type -- a closed mirror of IDA's `dref_t` (xref.hpp, IDA 9.3). A byte
/// outside this set does not decode -- its `TryFrom<u8>` conversion fails.
#[derive(
    Clone, Copy, Debug, PartialEq, Eq, Hash, TryFromPrimitive, IntoPrimitive, VariantArray,
)]
#[repr(u8)]
pub enum DataXref {
    /// `dr_U`: IDA's own "unknown" data type, kept for compatibility with old databases -- a
    /// real `dref_t` value, not a catch-all for unrecognized bytes.
    Unknown = 0,
    /// An offset (address-of) reference.
    Offset = 1,
    /// A write access.
    Write = 2,
    /// A read access.
    Read = 3,
    /// A textual reference (forced operands only).
    Text = 4,
    /// An informational reference.
    Informational = 5,
    /// `dr_S`: a reference to an enum member / symbolic constant.
    Symbolic = 6,
}

#[cfg(test)]
mod tests {
    use assert2::assert;
    use rstest::rstest;

    use super::*;

    /// The `(type, iscode)` byte pair classifies into the right space and variant, `iscode`
    /// selecting the space so the same byte reads differently as code vs data.
    #[rstest]
    #[case::call_near(17, 1, XrefKind::Code(CodeXref::CallNear))]
    #[case::jump_near(19, 1, XrefKind::Code(CodeXref::JumpNear))]
    #[case::flow(21, 1, XrefKind::Code(CodeXref::Flow))]
    #[case::data_write(2, 0, XrefKind::Data(DataXref::Write))]
    #[case::data_read(3, 0, XrefKind::Data(DataXref::Read))]
    #[case::symbolic(6, 0, XrefKind::Data(DataXref::Symbolic))]
    fn classifies_by_type_byte(#[case] ty: u8, #[case] iscode: u8, #[case] expect: XrefKind) {
        let x = Xref::from_raw(0x1000, 0x2000, ty, iscode, 0).expect("valid edge");
        assert!(x.kind == expect);
        assert!(x.is_code() == matches!(expect, XrefKind::Code(_)));
        assert!(x.from.get() == 0x1000);
        assert!(x.to.get() == 0x2000);
    }

    /// The `user` byte maps to [`XrefOrigin`]: nonzero is a user-defined edge, zero is one IDA's
    /// analysis generated.
    #[rstest]
    #[case::analysis(0, XrefOrigin::Analysis, false)]
    #[case::user(1, XrefOrigin::User, true)]
    fn origin_reflects_user_flag(
        #[case] user: u8,
        #[case] origin: XrefOrigin,
        #[case] is_user: bool,
    ) {
        let x = Xref::from_raw(0x1000, 0x2000, 3, 0, user).expect("valid edge");
        assert!(x.origin == origin);
        assert!(x.is_user() == is_user);
    }

    /// A type byte outside the `cref_t`/`dref_t` set does not decode, so the iterator skips it
    /// rather than folding it into a catch-all.
    #[rstest]
    #[case::unmapped_code(99, 1)]
    #[case::unmapped_data(99, 0)]
    fn unmapped_type_is_skipped(#[case] ty: u8, #[case] iscode: u8) {
        assert!(Xref::from_raw(0x1000, 0x2000, ty, iscode, 0).is_none());
    }

    /// Every modelled variant round-trips through its raw `cref_t`/`dref_t` discriminant, so a
    /// variant whose discriminant drifts from the SDK value fails here.
    #[test]
    fn every_variant_round_trips() {
        for &c in CodeXref::VARIANTS {
            assert!(CodeXref::try_from(u8::from(c)).ok() == Some(c));
        }
        for &d in DataXref::VARIANTS {
            assert!(DataXref::try_from(u8::from(d)).ok() == Some(d));
        }
    }

    /// A `BADADDR` at either endpoint is not a usable edge.
    #[test]
    fn badaddr_endpoint_is_rejected() {
        let bad = crate::address::BADADDR;
        assert!(Xref::from_raw(bad, 0x2000, 3, 0, 0).is_none());
        assert!(Xref::from_raw(0x1000, bad, 3, 0, 0).is_none());
    }
}
